# Script per ricreare sendClubEmail.js da zero con la base giusta

$srcFile = "c:\Users\paris\Downloads\play-sport-backup-2025-10-05_23-30-00\functions\sendBulkNotifications.clean.js"
$outFile = "c:\Users\paris\Downloads\play-sport-backup-2025-10-05_23-30-00\functions\sendClubEmail.js"

Write-Host "Copiando base da sendBulkNotifications.clean.js..." -ForegroundColor Cyan

# Leggi il file base (primi 100 lines - email config)
$baseLines = @(Get-Content $srcFile -Encoding UTF8 | Select-Object -First 100)

# Assembla il nuovo file
$newContent = @()

# Headers
$newContent += "// =============================================="
$newContent += "// FILE: functions/sendClubEmail.js"
$newContent += "// Cloud Function per invio email da club admin"
$newContent += "// Base da sendBulkNotifications.clean.js (funzionante)"
$newContent += "// =============================================="
$newContent += ""

# Aggiungi imports necessari (dalle linee 1-16 di sendBulkNotifications.clean.js)
$newContent += "import { onCall, HttpsError } from 'firebase-functions/v2/https';"
$newContent += "import { getApps, initializeApp } from 'firebase-admin/app';"
$newContent += "import { getFirestore } from 'firebase-admin/firestore';"
$newContent += "import sgMail from '@sendgrid/mail';"
$newContent += "import nodemailer from 'nodemailer';"
$newContent += ""

# Aggiungi init
$newContent += "if (getApps().length === 0) {"
$newContent += "  initializeApp();"
$newContent += "}"
$newContent += "const db = getFirestore();"
$newContent += ""

# Aggiungi getEmailConfig() (UGUALE a sendBulkNotifications.clean.js, linee 26-94)
$newContent += "let emailConfig = null;"
$newContent += ""
$newContent += "function getEmailConfig() {"
$newContent += "  if (!emailConfig) {"
$newContent += "    const SENDGRID_ENABLED = !!process.env.SENDGRID_API_KEY;"
$newContent += "    const NODEMAILER_ENABLED = !!(process.env.EMAIL_USER && process.env.EMAIL_PASSWORD);"
$newContent += "    const EMAIL_USER = process.env.EMAIL_USER || '';"
$newContent += "    const FROM_EMAIL = process.env.FROM_EMAIL || EMAIL_USER || 'noreplay@play-sport.pro';"
$newContent += "    "
$newContent += "    const emailUser = String(EMAIL_USER).toLowerCase();"
$newContent += "    const fromEmail = String(FROM_EMAIL).toLowerCase();"
$newContent += "    const useRegisterIt = emailUser.endsWith('@play-sport.pro') || fromEmail.endsWith('@play-sport.pro');"
$newContent += "    "
$newContent += "    console.log('🔧 [Email Config]', {"
$newContent += "      sendgridEnabled: SENDGRID_ENABLED,"
$newContent += "      nodemailerEnabled: NODEMAILER_ENABLED,"
$newContent += "      fromEmail: FROM_EMAIL,"
$newContent += "      provider: useRegisterIt ? 'Register.it' : 'Gmail',"
$newContent += "    });"
$newContent += ""
$newContent += "    if (SENDGRID_ENABLED) {"
$newContent += "      sgMail.setApiKey(process.env.SENDGRID_API_KEY);"
$newContent += "    }"
$newContent += ""
$newContent += "    let transporter = null;"
$newContent += "    if (NODEMAILER_ENABLED) {"
$newContent += "      if (useRegisterIt) {"
$newContent += "        const host = process.env.SMTP_HOST || 'smtp.register.it';"
$newContent += "        const port = process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT, 10) : 587;"
$newContent += "        const secure = process.env.SMTP_SECURE ? process.env.SMTP_SECURE === 'true' : false;"
$newContent += "        "
$newContent += "        transporter = nodemailer.createTransport({"
$newContent += "          host,"
$newContent += "          port,"
$newContent += "          secure,"
$newContent += "          requireTLS: true,"
$newContent += "          auth: {"
$newContent += "            user: process.env.EMAIL_USER,"
$newContent += "            pass: process.env.EMAIL_PASSWORD,"
$newContent += "          },"
$newContent += "          tls: {"
$newContent += "            rejectUnauthorized: false,"
$newContent += "          },"
$newContent += "          connectionTimeout: 30000,"
$newContent += "          greetingTimeout: 15000,"
$newContent += "          socketTimeout: 30000,"
$newContent += "          logger: true,"
$newContent += "        });"
$newContent += "      } else {"
$newContent += "        transporter = nodemailer.createTransport({"
$newContent += "          service: 'gmail',"
$newContent += "          auth: {"
$newContent += "            user: process.env.EMAIL_USER,"
$newContent += "            pass: process.env.EMAIL_PASSWORD,"
$newContent += "          },"
$newContent += "        });"
$newContent += "      }"
$newContent += "    }"
$newContent += ""
$newContent += "    emailConfig = {"
$newContent += "      sendgridEnabled: SENDGRID_ENABLED,"
$newContent += "      nodemailerEnabled: NODEMAILER_ENABLED,"
$newContent += "      fromEmail: FROM_EMAIL,"
$newContent += "      transporter,"
$newContent += "    };"
$newContent += "  }"
$newContent += "  return emailConfig;"
$newContent += "}"
$newContent += ""

# Aggiungi checkAdminPermissions
$newContent += "async function checkAdminPermissions(userId, clubId, userEmail) {"
$newContent += "  const clubRef = db.collection('clubs').doc(clubId);"
$newContent += "  const clubDoc = await clubRef.get();"
$newContent += "  "
$newContent += "  if (!clubDoc.exists) {"
$newContent += "    console.log('❌ [checkAdminPermissions] Club not found:', clubId);"
$newContent += "    return false;"
$newContent += "  }"
$newContent += "  "
$newContent += "  const club = clubDoc.data();"
$newContent += "  const requesterEmail = (userEmail || '').toLowerCase();"
$newContent += ""
$newContent += "  const isOwner = club?.ownerId === userId;"
$newContent += "  const isAdminFromClub = Array.isArray(club.admins) && club.admins.includes(userId);"
$newContent += "  const isAdminFromEmailList = Array.isArray(club.adminEmails) && requesterEmail ? club.adminEmails.map((e) => String(e).toLowerCase()).includes(requesterEmail) : false;"
$newContent += ""
$newContent += "  const membershipSnap = await clubRef.collection('users').where('userId', '==', userId).limit(1).get();"
$newContent += "  let isAdminFromMembership = false;"
$newContent += "  if (!membershipSnap.empty) {"
$newContent += "    const m = membershipSnap.docs[0].data();"
$newContent += "    isAdminFromMembership = m?.isClubAdmin === true || m?.role === 'admin' || m?.role === 'club_admin' || (Array.isArray(m?.roles) && (m.roles.includes('admin') || m.roles.includes('club_admin')));"
$newContent += "  }"
$newContent += ""
$newContent += "  const profileRef = clubRef.collection('profiles').doc(userId);"
$newContent += "  const profileDoc = await profileRef.get();"
$newContent += "  const isAdminFromProfile = profileDoc.exists ? profileDoc.data()?.isClubAdmin === true || profileDoc.data()?.role === 'club_admin' : false;"
$newContent += ""
$newContent += "  const affiliationId = \`\${userId}_\${clubId}\`;"
$newContent += "  const affiliationDoc = await db.collection('affiliations').doc(affiliationId).get();"
$newContent += "  const isAdminFromAffiliation = affiliationDoc.exists ? (affiliationDoc.data()?.role === 'club_admin' || affiliationDoc.data()?.isClubAdmin === true) && (affiliationDoc.data()?.status || 'approved') === 'approved' : false;"
$newContent += ""
$newContent += "  const isAdmin = isOwner || isAdminFromClub || isAdminFromEmailList || isAdminFromMembership || isAdminFromProfile || isAdminFromAffiliation;"
$newContent += "  console.log('🔐 [Permissions]', { clubId, uid: userId, isAdmin });"
$newContent += "  return isAdmin;"
$newContent += "}"
$newContent += ""

# Aggiungi sendEmailNotification
$newContent += "async function sendEmailNotification({ to, subject, html, clubName, replyTo }) {"
$newContent += "  const config = getEmailConfig();"
$newContent += "  console.log('📧 [sendClubEmail] Sending to:', to);"
$newContent += ""
$newContent += "  if (config.nodemailerEnabled && config.transporter) {"
$newContent += "    try {"
$newContent += "      console.log('📧 [sendClubEmail] Attempting Nodemailer...');"
$newContent += "      await config.transporter.sendMail({"
$newContent += "        from: \`\\\"\${clubName}\\\" <\${config.fromEmail}>\`,"
$newContent += "        to,"
$newContent += "        replyTo: replyTo || config.fromEmail,"
$newContent += "        subject,"
$newContent += "        html,"
$newContent += "      });"
$newContent += "      console.log('✅ [sendClubEmail] Sent via Nodemailer');"
$newContent += "      return { provider: 'nodemailer', success: true };"
$newContent += "    } catch (smtpError) {"
$newContent += "      console.warn('⚠️ [sendClubEmail] Nodemailer failed:', smtpError.message);"
$newContent += "    }"
$newContent += "  }"
$newContent += ""
$newContent += "  if (config.sendgridEnabled) {"
$newContent += "    try {"
$newContent += "      console.log('📧 [sendClubEmail] Attempting SendGrid...');"
$newContent += "      await sgMail.send({"
$newContent += "        from: { email: config.fromEmail, name: clubName },"
$newContent += "        to,"
$newContent += "        replyTo: replyTo || config.fromEmail,"
$newContent += "        subject,"
$newContent += "        html,"
$newContent += "      });"
$newContent += "      console.log('✅ [sendClubEmail] Sent via SendGrid');"
$newContent += "      return { provider: 'sendgrid', success: true };"
$newContent += "    } catch (sendgridError) {"
$newContent += "      console.error('❌ [sendClubEmail] SendGrid failed:', sendgridError.message);"
$newContent += "      throw new Error(\`Email delivery failed: \${sendgridError.message}\`);"
$newContent += "    }"
$newContent += "  }"
$newContent += ""
$newContent += "  throw new Error('No email provider configured');"
$newContent += "}"
$newContent += ""

# Main Cloud Function
$newContent += "export const sendClubEmail = onCall("
$newContent += "  {"
$newContent += "    region: 'us-central1',"
$newContent += "    memory: '256MiB',"
$newContent += "    timeoutSeconds: 300,"
$newContent += "    secrets: ['EMAIL_USER', 'EMAIL_PASSWORD', 'FROM_EMAIL'],"
$newContent += "  },"
$newContent += "  async (request) => {"
$newContent += "    if (!request.auth) {"
$newContent += "      throw new HttpsError('unauthenticated', 'User must be authenticated');"
$newContent += "    }"
$newContent += ""
$newContent += "    const userId = request.auth.uid;"
$newContent += "    const userEmail = request.auth.token.email || 'unknown';"
$newContent += "    const { clubId, recipients, subject, body, isHTML = false, replyTo } = request.data;"
$newContent += ""
$newContent += "    console.log('📧 [sendClubEmail] Request:', { clubId, recipientsCount: recipients?.length, subject });"
$newContent += ""
$newContent += "    if (!clubId) throw new HttpsError('invalid-argument', 'clubId is required');"
$newContent += "    if (!recipients || !Array.isArray(recipients) || recipients.length === 0) {"
$newContent += "      throw new HttpsError('invalid-argument', 'recipients array is required');"
$newContent += "    }"
$newContent += "    if (!subject || !body) throw new HttpsError('invalid-argument', 'subject and body are required');"
$newContent += ""
$newContent += "    const isAdmin = await checkAdminPermissions(userId, clubId, userEmail);"
$newContent += "    if (!isAdmin) {"
$newContent += "      console.warn('⚠️ [sendClubEmail] Permission denied:', { userId, clubId });"
$newContent += "      throw new HttpsError('permission-denied', 'User is not admin of this club');"
$newContent += "    }"
$newContent += ""
$newContent += "    const clubRef = db.collection('clubs').doc(clubId);"
$newContent += "    const clubDoc = await clubRef.get();"
$newContent += "    if (!clubDoc.exists) throw new HttpsError('not-found', 'Club not found');"
$newContent += ""
$newContent += "    const club = clubDoc.data();"
$newContent += "    const clubName = club.name || 'Play-Sport';"
$newContent += "    const clubReplyTo = replyTo || club.contactEmail || club.email || 'info@sportingcat.it';"
$newContent += ""
$newContent += "    const emailList = [];"
$newContent += "    for (const recipient of recipients) {"
$newContent += "      try {"
$newContent += "        if (typeof recipient === 'string') {"
$newContent += "          const playerRef = db.collection('clubs').doc(clubId).collection('users').doc(recipient);"
$newContent += "          const playerDoc = await playerRef.get();"
$newContent += "          if (playerDoc.exists) {"
$newContent += "            const player = playerDoc.data();"
$newContent += "            if (player.email) emailList.push({ email: player.email, name: player.displayName || player.name || 'Player' });"
$newContent += "          } else {"
$newContent += "            const globalUserRef = db.collection('users').doc(recipient);"
$newContent += "            const globalUserDoc = await globalUserRef.get();"
$newContent += "            if (globalUserDoc.exists) {"
$newContent += "              const user = globalUserDoc.data();"
$newContent += "              if (user.email) emailList.push({ email: user.email, name: user.displayName || user.firstName || 'Player' });"
$newContent += "            }"
$newContent += "          }"
$newContent += "        } else if (recipient && recipient.email) {"
$newContent += "          emailList.push({ email: recipient.email, name: recipient.name || 'Player' });"
$newContent += "        }"
$newContent += "      } catch (error) {"
$newContent += "        console.warn('⚠️ Error resolving recipient:', error.message);"
$newContent += "      }"
$newContent += "    }"
$newContent += ""
$newContent += "    if (emailList.length === 0) throw new HttpsError('invalid-argument', 'No valid recipients found');"
$newContent += ""
$newContent += "    const results = { success: true, sent: 0, failed: 0, details: [] };"
$newContent += ""
$newContent += "    for (const recipient of emailList) {"
$newContent += "      try {"
$newContent += "        const result = await sendEmailNotification({"
$newContent += "          to: recipient.email,"
$newContent += "          subject,"
$newContent += "          html: isHTML ? body : \`<p>\${body.split('\\n').join('</p><p>')}</p>\`,"
$newContent += "          clubName,"
$newContent += "          replyTo: clubReplyTo,"
$newContent += "        });"
$newContent += ""
$newContent += "        results.sent++;"
$newContent += "        results.details.push({ email: recipient.email, name: recipient.name, success: true, provider: result.provider });"
$newContent += "        console.log(\`✅ Email sent to \${recipient.email}\`);"
$newContent += "        await new Promise(resolve => setTimeout(resolve, 200));"
$newContent += "      } catch (error) {"
$newContent += "        console.error(\`❌ Failed to send to \${recipient.email}: \${error.message}\`);"
$newContent += "        results.failed++;"
$newContent += "        results.details.push({ email: recipient.email, name: recipient.name, success: false, error: error.message });"
$newContent += "      }"
$newContent += "    }"
$newContent += ""
$newContent += "    results.success = results.failed === 0;"
$newContent += "    console.log('📊 [sendClubEmail] Results:', { sent: results.sent, failed: results.failed });"
$newContent += "    return results;"
$newContent += "  }"
$newContent += ");"

# Scrivi il file con encoding UTF8 (no BOM)
$utf8NoBOM = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($outFile, $newContent, $utf8NoBOM)

Write-Host "✅ File ricreato: $outFile" -ForegroundColor Green
Write-Host "📊 Linee scritte: $($newContent.Count)" -ForegroundColor Cyan
